enum Avoid_ActionType {
  "Avoid::ShapeMove",
  "Avoid::ShapeAdd",
  "Avoid::ShapeRemove",
  "Avoid::JunctionMove",
  "Avoid::JunctionAdd",
  "Avoid::JunctionRemove",
  "Avoid::ConnChange",
  "Avoid::ConnectionPinChange"
};

// TODO: ConnUpdateList

typedef sequence<ActionInfo> ActionInfoList;

[Prefix="Avoid::"]
interface ActionInfo {
  void ActionInfo(Avoid_ActionType t, ShapeRef s, [Ref] Polygon p, boolean fm);
  void ActionInfo(Avoid_ActionType t, ShapeRef s);
  void ActionInfo(Avoid_ActionType t, JunctionRef s, [Ref] Point p);
  // TODO: 3 more constructors

  Obstacle obstacle();
  ShapeRef shape();
  ConnRef conn();
  JunctionRef junction();
  void addConnEndUpdate(unsigned long type, [Ref] ConnEnd connEnd, boolean isConnPinMoveUpdate);
  // TODO: operators

  attribute Avoid_ActionType type;
  attribute VoidPtr objPtr;
  [Value] attribute Polygon newPoly;
  [Value] attribute Point newPosition;
  attribute boolean firstMove;
  // TODO: conns
};
