// TODO: typedefs

[Prefix="Avoid::"]
interface HyperedgeTreeNode {
  void HyperedgeTreeNode();

  void writeEdgesToConns(HyperedgeTreeEdge ignored, unsigned long pass);
  // void listJunctionsAndConnectors(HyperedgeTreeEdge ignored,
  //     [Ref] sequence<JunctionRefList> junctions, [Ref] ConnRefList connectors);
};

[Prefix="Avoid::"]
interface HyperedgeTreeEdge {
  void HyperedgeTreeEdge(HyperedgeTreeNode node1, HyperedgeTreeNode node2,
      ConnRef conn);
};
